Complete Desktop version pull request
Sohail-Aslam/Mobile-Version pull request #3
Opened 2023-08-02 12:29 UTC by Sohail-Aslam

- [ ] Responsive website 
- [ ] Use media queries in CSS file
- [ ] Grid and Flexbox are used to lay out the elements on the page.

2023-08-04 10:49 UTC, emhamza requested changes
**Hi @Sohail-Aslam 👍 

Required Changers** ♻️ 
Good Job so far, There is something that you need to change before go to the next project, Please consider my comments in the section below

![so-close-reaching-out](https://github.com/Sohail-Aslam/Mobile-Version/assets/122353030/3453637b-0b7a-4b0d-86d5-f16f6942be6c)

2023-08-04 10:49 UTC, emhamza commented on index.css
> +@media (min-width: 750px) {
@Sohail-Aslam Good job so far but i would suggest you to correct your media query break point, and make it similar to the given instructions 🦖 

`Use media queries in your CSS file to make your desktop version look like the template you selected (Desktop: >=768px).`

![sohail-styler](https://github.com/Sohail-Aslam/Mobile-Version/assets/122353030/da6358be-602b-4bbf-bd4a-5407777d8fe4)

2023-08-04 10:49 UTC, emhamza commented on index.html
> +                <a href="" class="more"><img src="hero/humberger.png" height="25px"  alt=""></a>
@Sohail-Aslam i would suggest to check the break point of your desktop version menu: Since it is not showing expected:

2023-08-04 10:49 UTC, emhamza commented on index.html
> +            <hr class="line">
@Sohail-Aslam Your size/spacing is not matching to the original design please consider to make it similar 🆒 😎 
![sohail-2](https://github.com/Sohail-Aslam/Mobile-Version/assets/122353030/47037fa8-f2f9-4d0e-9dd8-48a62dc66f43)

2023-08-07 12:35 UTC, Muhammad-UsmanTariq commented
**Hi @Sohail-Aslam 👍

Required Changers** ♻️
Good Job so far, There is something that you need to change before go to the next project, Please consider my comments in the section below

https://user-images.githubusercontent.com/122353030/258399306-3453637b-0b7a-4b0d-86d5-f16f6942be6c.gif

2023-08-07 12:40 UTC, Muhammad-UsmanTariq commented
@Sohail-Aslam  Good job so far but i would suggest you to fix the padding and margin according to the figma templete .

https://user-images.githubusercontent.com/122353030/258398500-47037fa8-f2f9-4d0e-9dd8-48a62dc66f43.JPG

2023-08-07 12:43 UTC, Muhammad-UsmanTariq commented
**Hi @Sohail-Aslam  I would suggest you to fix this.

![Screenshot 2023-08-04 184203](https://github.com/Sohail-Aslam/Mobile-Version/assets/138443733/ac4bf368-5b5d-44f5-83ca-0b06a3434c3e)

2023-08-08 07:22 UTC, Muhammad-UsmanTariq commented
Hi @Sohail-Aslam I approved this project. Happy Coding!


![Approved](https://github.com/Sohail-Aslam/Mobile-Version/assets/138443733/b13adfbd-bc1b-4690-bcea-1f7adb6471bb)

2023-08-08 07:59 UTC, merged